export type IconCategory =
  | 'calendar'
  | 'rating'
  | 'search'
  | 'full-star'
  | 'empty-star'
  | 'half-star'
  | 'fill-heart'
  | 'empty-heart'
  | 'back'
  | 'close'
  | 'drag'
  | 'edit'

export type Status = 'ADD' | 'REMOVE' | 'CREATE'
